### PR TITLE
Sean's branch

### PR DESCRIPTION
**Pull request by dacamor**
# Steps To Test #
1. Pull down TestingBranch
2. Test PUT, POST, DELETE, GET for Computer, EmployeeComputer, ShoppingCart, and OrderedProducts
3. Test PUT, POST, GET for departments

[Hyperlink to ticket](http://www.google.fr/)

### Description of what should happen when steps are followed ###
The Database should update with the appropriate data.
**At least one person needs to approve pull request before merged to master**

### CODE REVIEW

**Comment by kimberly-bird** [comment]
👍  on departments. POST, PUT, GET worked for me

**Comment by tgbowman** [comment]
Getting a 500 ServerError when trying to POST an employeeComputer the error is saying:
SQLite Error 19: 'NOT NULL constraint failed: EmployeeComputer.IssueDate'.
However, I am sending the db an issue date so it shouldn't recognizing it as null

**Comment by krnorris65** [comment]
GET single shopping cart is not working. I get the following error: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLB4TNVN9BBO", Request id "0HLB4TNVN9BBO:00000001": An unhandled exception was thrown by the application.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: OrderedProducts'.
I think the issue may be on line 49 in the controller because when I comment it out, it works.

**Comment by krnorris65** [comment]
POST shopping cart isn't working. I get the following error telling me that DateCreated can't be null, but the field is supposed to autogenerate.
Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLB4TPB45RK2", Request id "0HLB4TPB45RK2:00000001": An unhandled exception was thrown by the application.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'NOT NULL constraint failed: ShoppingCart.DateCreated'.

**Comment by krnorris65** [comment]
Also, it would be helpful to change the comments to reflect what the controller is related to. on line 188 the method is called "DeleteEmployeeTraining" so that should be changed to reflect what it's actually doing (deleting a product from the order).

The functionality of the GET  list of shopping carts, PUT and DELETE methods, adding/deleting products to/from an order seem to be fine. Just issues that I listed above with the GET of a single shopping cart and POST a shopping cart

**Comment by krnorris65** [comment]
👍

**Pull request merged**
